spring:
  application:
    name: cards-application-processor

  cassandra:
    port: 9042
    contact-points: mycassandra
    local-datacenter: datacenter1
    keyspace-name: cards
    schema-action: create_if_not_exists
  kafka:
    bootstrap-servers:
      - "localhost:19092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: true
topics:
  application-submitted-event: vnd_cards_application_submitted_event
  application-validated-event: vnd_cards_application_validated_event


